config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resource :exchange_logs, only: [:create]
    end
  end

  resource :rates, only: [:index] do
    get :month, on: :collection
    get :day, on: :collection
    get :hour, on: :collection
  end
  root to: 'rates#index'
end

app/models/rates/average.rb
module Rates
  class Average
    attr_reader :usd, :gbp, :eur

    private

    def initialize(usd, gbp, eur)
      @usd = usd
      @gbp = gbp
      @eur = eur
    end

    class << self
      def add_exchange(exchange)
        SavedAverage.kinds.each_key do |kind|
          key = build_key(kind, exchange.updated)
          create_or_update(kind, key, exchange)
        end
      end

      def day(timestamp)
        candidate = SavedAverage.find_by(kind: :day, key: build_key(:day, timestamp))
        calculate(candidate)
      end

      def hour(timestamp)
        candidate = SavedAverage.find_by(kind: :hour, key: build_key(:hour, timestamp))
        calculate(candidate)
      end

      def minute(timestamp)
        candidate = SavedAverage.find_by(kind: :minute, key: build_key(:minute, timestamp))
        calculate(candidate)
      end

      private

      def calculate(candidate)
        return null_object if candidate.nil?

        new(
          divide_or_zero(candidate.usd_sum, candidate.usd_count),
          divide_or_zero(candidate.gbp_sum, candidate.gbp_count),
          divide_or_zero(candidate.eur_sum, candidate.eur_count)
        )
      end

      def null_object
        new(0, 0, 0)
      end

      def build_key(kind, timestamp)
        case kind.to_sym
        when :day
          timestamp.strftime('%Y%m%d000000')
        when :hour
          timestamp.strftime('%Y%m%d%H0000')
        when :minute
          timestamp.strftime('%Y%m%d%H%M00')
        end
      end

      def create_or_update(kind, key, exchange)
        candidate = SavedAverage.create_or_find_by(kind: kind, key: key)
        candidate.usd_sum += exchange.usd_rate
        candidate.usd_count += 1
        candidate.gbp_sum += exchange.gbp_rate
        candidate.gbp_count += 1
        candidate.eur_sum += exchange.eur_rate
        candidate.eur_count += 1
        candidate.save!
      end

      def divide_or_zero(divident, divisor)
        if divisor.zero?
          0
        else
          divident.fdiv divisor
        end
      end
    end
  end
end

app/models/rates/min_max.rb
module Rates
  class MinMax
    attr_reader :min, :max

    private

    def initialize(min, max)
      @min = min
      @max = max
    end

    class << self
      def usd(start, finish)
        calculate(:usd, start, finish)
      end

      def gbp(start, finish)
        calculate(:gbp, start, finish)
      end

      def eur(start, finish)
        calculate(:eur, start, finish)
      end

      private

      def calculate(currency, start, finish)
        result = ExchangeLog.where('updated between ? and ?', start, finish).pluck("#{currency}_rate")
        if result.empty?
          null_object
        else
          new(
            result.min,
            result.max
          )
        end
      end

      def null_object
        new(0, 0)
      end
    end
  end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  include HasBreadcrumbs

  def index; end

  def month
    process_request(:month)
  end

  def day
    process_request(:day)
  end

  def hour
    process_request(:hour)
  end

  private

  def process_request(time_frame)
    request =
      case time_frame
      when :month
        Services::Graph::Month.call
      when :day
        Services::Graph::Day.call
      when :hour
        Services::Graph::Hour.call
      end
    if request.success?
      render json: request.result, status: :ok
    else
      render json: { error: request.erors }, status: :service_unavailable
    end
  end

  def set_breadcrumbs
    add_breadcrumbs(
      [
        ['Home', root_path], ['Exchange rates']
      ]
    )
  end
end

app/views/rates/index.html.slim
.container-fluid
  .animated.fade-in
    .card data-controller="charts background-update"
      .card-header
        h1
          | BitCoin rate history
        small
          a.h5 href="https://www.coindesk.com/price/bitcoin" target="_blank"
            | Powered by CoinDesk

      .card-body
        .d-flex.justify-content-end
          .btn-group.justify-content-end[role="group"]
            button.btn.btn-outline-primary.time-nav[
              type="button"
              data-action="click->charts#fetchGraphData"
              data-url="#{month_rates_path}"
              data-charts-target="month"
            ]
              | 30 days
            button.btn.btn-outline-primary.time-nav.active[
              type="button"
              data-action="click->charts#fetchGraphData"
              data-url="#{day_rates_path}"
              data-charts-target="day"
            ]
              | 24 hours
            button.btn.btn-outline-primary.time-nav[
              type="button"
              data-action="click->charts#fetchGraphData"
              data-url="#{hour_rates_path}"
              data-charts-target="hour"
            ]
              | Last hour

        .c-chart-wrapper
          .chartjs-size-monitor
            .chartjs-size-monitor-expand
              div
            .chartjs-size-monitor-shrink
              div
          canvas#btc-chart.chart.chartjs-render-monitor[
            height="600"
            width="1549"
            style="display: block;"
            data-charts-target="chart"
          ]